"""initial schema

Revision ID: 1adc6ae96adc
Revises:
Create Date: 2026-08-04 14:14:55.634197
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1adc6ae96adc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_name"), ["name"], unique=True)

    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "hash", name="uq_prompt_project_hash"),
    )
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.create_index("ix_prompt_project_version", ["project_id", "version"], unique=False)
        batch_op.create_index(batch_op.f("ix_prompt_versions_hash"), ["hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_prompt_versions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
        sa.Column("function_name", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("user_input", sa.Text(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("env", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_runs_model", ["model"], unique=False)
        batch_op.create_index("ix_runs_project_created", ["project_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index("ix_runs_prompt_version", ["prompt_version_id"], unique=False)
        batch_op.create_index("ix_runs_provider", ["provider"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_provider")
        batch_op.drop_index("ix_runs_prompt_version")
        batch_op.drop_index(batch_op.f("ix_runs_project_id"))
        batch_op.drop_index("ix_runs_project_created")
        batch_op.drop_index("ix_runs_model")
        batch_op.drop_index(batch_op.f("ix_runs_created_at"))

    op.drop_table("runs")
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_versions_project_id"))
        batch_op.drop_index(batch_op.f("ix_prompt_versions_hash"))
        batch_op.drop_index("ix_prompt_project_version")

    op.drop_table("prompt_versions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_name"))

    op.drop_table("projects")
    # ### end Alembic commands ###
